### ISSUE TITLE
Add javascript to Weblate

### ISSUE THREAD

**Issue by Apollon77** [ioBrokerTranslator/requests#26]
**Checklist:**

-   [X] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [X] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [X] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)
-  [x] translate checked

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.javascript
URL: https://github.com/ioBroker/ioBroker.javascript

**Remarks:**
i18n files at https://github.com/ioBroker/ioBroker.javascript/tree/master/src/src/i18n (like web)

**Comment by Apollon77** [comment]
BTW: DO we have any way toalso get https://github.com/ioBroker/ioBroker.javascript/blob/master/admin/adminWords.js in it? (yes I can also create i18n dir, but then we have two ...)

**Comment by UncleSamSwiss** [comment]
There are three parts to be translated:
- https://github.com/ioBroker/ioBroker.javascript/tree/master/src/src/i18n
- https://github.com/ioBroker/ioBroker.javascript/blob/master/admin/adminWords.js (which is currently missing the JSON files)
- https://github.com/ioBroker/ioBroker.javascript/tree/master/admin-config/i18n

For these, we can create three different "components" in Weblate, but the question is, is this meaningful?
Translations should IMHO be in the same file for all parts of the adapter as some strings may otherwise be translated differently.
Also, if we want the adminWords.js, you need to add to the gulpfile a way to generate the words.js from the JSON files (and init the JSON files once).

**Comment by Apollon77** [comment]
We need:
* https://github.com/ioBroker/ioBroker.javascript/tree/master/src/src/i18n
* https://github.com/ioBroker/ioBroker.javascript/tree/master/admin-config/i18n ...

The https://github.com/ioBroker/ioBroker.javascript/blob/master/admin/adminWords.js is just a copy by build process and can be ignored here.

The gulp task exists ... https://github.com/ioBroker/ioBroker.javascript/blob/master/gulpfile.js#L764
So two

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.javascript was added to Weblate:
https://weblate.iobroker.net/projects/adapters/javascript/
https://weblate.iobroker.net/projects/adapters/javascript-tab/ (linked to the above)

Please add **both** badges for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
